import createClient, { Middleware } from "openapi-fetch";
import type { paths } from "./v1.d.ts"; // generated by openapi-typescript

const middleware: Middleware = {
  async onRequest({ request }) {
    request.headers.set("Content-Type", "application/json");
    request.headers.set("Accept", "application/json");
    request.headers.set(
      "Authorization",
      `Bearer ${process.env.NEXT_PUBLIC_TMDB_API_KEY}`
    );
    return request;
  },
  async onResponse({ response }) {
    return response;
  },
  async onError({ error }) {
    return new Error("Oops, fetch failed", { cause: error });
  },
};

const client = createClient<paths>({
  baseUrl: "https://api.themoviedb.org",
});
client.use(middleware);

export default client;
