import TextField from "@/components/common/TextField";
import "./globals.css";
import { Poppins } from "next/font/google";
import clsx from "clsx";
import { Search } from "react-feather";

const inter = Poppins({ weight: "400", subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav className="px-4 w-full bg-slate-100 fixed top-0 left-0 z-50 h-[8vh]">
          <TextField
            startIcon={<Search />}
            containerClassName="h-full"
            className="bg-transparent"
            placeholder="Search movies here..."
            value=""
            onChange={() => {}}
          />
        </nav>
        <main className="pt-[8vh]">{children}</main>
      </body>
    </html>
  );
}
